baseURL = "https://silent-souls.com"
languageCode = "en-us"
title = "Silent Souls - Electronic Music Duo"
theme = "silentsouls"
publishDir = "docs"

[params]
  description = "Silent Souls - Techno project from Madeira Island, formed by Leo Oliveira and Carlos Azevedo (aka Zen). Peak-time techno with hypnotic and psychedelic influences."
  author = "Silent Souls"

  [params.analytics]
    goatcounter = "silentsouls" # Your GoatCounter code (silentsouls.goatcounter.com)

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false